apiVersion: v1
kind: Namespace
metadata:
  name: opoplan
  labels:
    name: opoplan
    app.kubernetes.io/part-of: opoplan
  annotations:
    openshift.io/display-name: "OpoPlan — CGD"
    openshift.io/description: "Plataforma multi-tenant de preparación de oposiciones"
